restart_container:
  name: DCC Restart Container
  description: "Restart a Docker Compose container"
  fields:
    entity_id:
      name: Entity ID
      description: "The entity ID of the container sensor"
      required: true
      example: "sensor.homeassistant"
