restart_service:
  name: Restart Service
  description: "Restart a Docker Compose service"
  fields:
    entry_id:
      name: Service Entity ID
      description: "The configuration entry ID"
      required: true
      example: "123abc"
